FROM httpd:2.4

COPY resources/usr/local/apache2/conf/httpd.conf /usr/local/apache2/conf/httpd.conf
COPY resources/usr/local/apache2/sites-enabled/symfony.localhost.conf /usr/local/apache2/sites-enabled/symfony.localhost.conf
